# The below is required in order to support redirects (see the following URLs for details):
#   https://help.github.com/articles/redirects-on-github-pages/
#   https://help.github.com/articles/using-jekyll-plugins-with-github-pages/
gems:
  - jekyll-redirect-from
